const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('crypto');const fs=require('fs');const {PGlite}=require('@electric-sql/pglite');
const {billing}=require('../services/paymongo-billing/service.cjs');const {verify,assertRuntime}=require('../services/paymongo-billing/security.cjs');const {provider}=require('../services/paymongo-billing/provider.cjs');const {termEnd}=require('../services/paymongo-billing/subscription-domain.cjs');
const now=new Date('2026-09-13T04:00:00Z');
async function setup(){const pg=new PGlite();await pg.exec(`CREATE SCHEMA gethired;CREATE TABLE gethired.companies(company_id VARCHAR PRIMARY KEY,created_by VARCHAR);CREATE TABLE gethired.user_credentials(uid VARCHAR PRIMARY KEY,role INT,is_archive BOOLEAN DEFAULT FALSE);CREATE TABLE gethired.company_employees(company_id VARCHAR,employee_uuid VARCHAR);CREATE TABLE gethired.jobs(job_id VARCHAR,company_id VARCHAR,job_status_id INT);CREATE TABLE gethired.companies_subscription(company_id VARCHAR,subscription_id INT,created_at TIMESTAMPTZ DEFAULT NOW(),payment_date TIMESTAMPTZ,period_start TIMESTAMPTZ,period_end TIMESTAMPTZ,sub_status VARCHAR,is_paid BOOLEAN,plan_slug VARCHAR,billing_cycle VARCHAR);`);
for(const file of ['20260831_notifications.sql','subscription_engagement_migration.sql','payment_webhook_events_ddl.sql','20260630_invoice_billing_schema.sql','paymongo_billing_migration.sql','paymongo_billing_migration.sql'])await pg.exec(fs.readFileSync('db/'+file,'utf8'));
await pg.exec(`INSERT INTO gethired.companies VALUES('a','owner'),('b','other');INSERT INTO gethired.user_credentials(uid,role) VALUES('owner',2),('other',2),('recruiter',2),('candidate',3);INSERT INTO gethired.company_employees VALUES('a','owner'),('a','recruiter'),('b','other');INSERT INTO gethired.companies_subscription(company_id,subscription_id,plan_slug,is_paid,sub_status,period_start,period_end,billing_cycle,engagement_plan_version) VALUES('a',1,'free_trial',FALSE,'trialing','2026-09-01','2026-09-15','monthly','pricing_2026_09');`);
const config={catalogVersion:'pricing_2026_09',enabled:true,mode:'test',nodeEnv:'test',dbHost:'localhost',webhookSecret:crypto.randomBytes(32).toString('hex'),clock:()=>now};let calls=0;let last;
const mock={createLink:async a=>{calls++;last=a;return {linkId:'link_'+a.id,referenceNumber:'ref_'+a.id,checkoutUrl:'https://pm.link/'+a.id};},retrieveLink:async()=>lastResource};let lastResource;
const s=billing(pg,'gethired',config,mock);const c=await s.resolve('owner');
function event(a,{type='payment.paid',amount=a.amountMinor,currency='PHP',paymentId='pay_'+a.paymentAttemptId,eventId='evt_'+crypto.randomBytes(10).toString('hex'),reference,livemode=false}={}){const resource={id:paymentId,type:'payment',attributes:{amount,currency,status:type==='payment.failed'?'failed':'paid',livemode,metadata:{internal_payment_reference:reference || last.internal_reference},source:{type:'gcash'}}};return {data:{id:eventId,type:'event',attributes:{type,livemode,data:resource}}};}
function signed(e,stamp=Math.floor(+now/1000)){const raw=Buffer.from(JSON.stringify(e));const sig=crypto.createHmac('sha256',config.webhookSecret).update(stamp+'.').update(raw).digest('hex');return [raw,'t='+stamp+',te='+sig];}
return {pg,s,c,config,event,signed,calls:()=>calls,setResource:r=>lastResource=r,last:()=>last,close:()=>pg.close()};}
async function count(pg,table){return (await pg.query('SELECT COUNT(*)::int AS n FROM gethired.'+table)).rows[0].n;}
test('signed paid conversion commits exactly one transaction, invoice and fulfillment across event IDs; late failure ignored',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'growth'});assert.equal(a.amountMinor,299000);assert.equal((await f.s.effective(f.c)).status,'trialing');assert.deepEqual(await f.s.checkout(f.c,{planCode:'growth'}),a);assert.equal(f.calls(),1);const e=f.event(a);assert.equal((await f.s.webhook(...f.signed(e))).status,'PROCESSED');assert.equal((await f.s.webhook(...f.signed(e))).status,'DUPLICATE');assert.equal((await f.s.webhook(...f.signed(f.event(a)))).status,'DUPLICATE');assert.equal((await f.s.webhook(...f.signed(f.event(a,{type:'payment.failed'})))).status,'DUPLICATE');for(const t of ['payment_transactions','invoices','billing_fulfillments','subscription_billing_history'])assert.equal(await count(f.pg,t),1,t);const effective=await f.s.effective(f.c);assert.equal(effective.entitlements.storage,50000000000);assert.equal(effective.entitlements.jobs,15);assert.equal(effective.planCode,'growth');assert.equal((await f.s.history(f.c)).items[0].amountMinor,299000);assert.equal((await f.s.status(f.c,a.paymentAttemptId)).status,'PAID');await assert.rejects(()=>f.s.status({companyId:'b'},a.paymentAttemptId),{code:'PAYMENT_ATTEMPT_NOT_FOUND'});await assert.rejects(()=>f.s.resolve('recruiter'),{httpStatus:403});await assert.rejects(()=>f.s.resolve('candidate'),{httpStatus:403});}finally{await f.close();}});
test('signature boundaries reject missing, stale, wrong mode, malformed, mutated and forged signatures before ledger mutation',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'starter'});const e=f.event(a);const [raw,h]=f.signed(e);for(const args of [[raw,undefined],[raw,h.replace('te=','li=')],[raw,h.replace(/te=.*/,'te=no')],[Buffer.concat([raw,Buffer.from(' ')]),h],f.signed(e,Math.floor(+now/1000)-301),f.signed({...e,data:{...e.data,attributes:{...e.data.attributes,livemode:true}}})])await assert.rejects(()=>f.s.webhook(...args));assert.equal(await count(f.pg,'payment_webhook_events'),0);assert.throws(()=>assertRuntime({...f.config,dbHost:'production.example'}));assert.throws(()=>assertRuntime({...f.config,mode:'live'}));assert.throws(()=>assertRuntime({...f.config,enabled:false}));}finally{await f.close();}});
test('amount, currency and cross-company reference mismatches enter review without activation; unknown verified event acknowledged',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'starter'});for(const opt of [{amount:1},{currency:'USD'},{reference:'GH_PAY_'+crypto.randomBytes(16).toString('hex')}])assert.equal((await f.s.webhook(...f.signed(f.event(a,opt)))).status,'REVIEW');assert.equal(await count(f.pg,'payment_transactions'),0);assert.equal((await f.s.effective(f.c)).status,'trialing');const e=f.event(a,{type:'payment.refunded'});assert.equal((await f.s.webhook(...f.signed(e))).status,'IGNORED');await assert.rejects(()=>f.s.checkout(f.c,{planCode:'growth',amount:1}),{code:'PAYMENT_REQUEST_INVALID'});await assert.rejects(()=>f.s.checkout(f.c,{planCode:'enterprise'}),{code:'INVALID_PLAN'});await assert.rejects(()=>f.s.checkout(f.c,{planCode:'starter',billingCycle:'annual'}),{code:'BILLING_PRICE_NOT_APPROVED'});}finally{await f.close();}});
test('failed then paid recovers, extra paid identity enters review; failed processing rolls back and same event retries',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'starter'});await f.s.webhook(...f.signed(f.event(a,{type:'payment.failed'})));assert.equal((await f.s.status(f.c,a.paymentAttemptId)).status,'FAILED');assert.equal((await f.s.effective(f.c)).status,'trialing');const e=f.event(a);await f.pg.exec(`CREATE FUNCTION gethired.reject_invoice() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'injected failure'; END $$;CREATE TRIGGER reject_invoice BEFORE INSERT ON gethired.invoices FOR EACH ROW EXECUTE FUNCTION gethired.reject_invoice();`);await assert.rejects(()=>f.s.webhook(...f.signed(e)),{code:'PAYMONGO_PROCESSING_FAILED'});assert.equal(await count(f.pg,'payment_transactions'),0);assert.equal((await f.s.effective(f.c)).status,'trialing');await f.pg.exec('DROP TRIGGER reject_invoice ON gethired.invoices');assert.equal((await f.s.webhook(...f.signed(e))).status,'PROCESSED');assert.equal((await f.s.webhook(...f.signed(f.event(a,{paymentId:'pay_second'})))).status,'REVIEW');assert.equal(await count(f.pg,'invoices'),1);}finally{await f.close();}});
test('upgrades and storage add-ons use paid entitlements; addon increases Growth from 50 GB to 75 GB once',async()=>{const f=await setup();try{let a=await f.s.checkout(f.c,{planCode:'starter'});await f.s.webhook(...f.signed(f.event(a)));a=await f.s.checkout(f.c,{planCode:'growth'});assert.equal((await f.s.effective(f.c)).entitlements.jobs,5);await f.s.webhook(...f.signed(f.event(a)));await assert.rejects(()=>f.s.checkout(f.c,{planCode:'starter'}),{code:'UPGRADE_NOT_ALLOWED'});a=await f.s.checkout(f.c,{packageCode:'storage_25'});assert.equal(a.amountMinor,49900);assert.equal((await f.s.effective(f.c)).entitlements.storage,50000000000);const e=f.event(a);await f.s.webhook(...f.signed(e));await f.s.webhook(...f.signed(e));assert.equal((await f.s.effective(f.c)).entitlements.storage,75000000000);assert.equal(await count(f.pg,'subscription_storage_addons'),1);await assert.rejects(()=>f.s.checkout(f.c,{packageCode:'storage_25'}),{code:'ADDON_ALREADY_ACTIVE'});}finally{await f.close();}});
test('grandfathered renewal preserves stored agreement, key reuse stable and approved annual uses exact amount',async()=>{const f=await setup();try{await f.pg.exec(`INSERT INTO gethired.billing_plan_versions(id,plan_code,catalog_version,legacy_subscription_id,monthly_minor,entitlements) VALUES('legacy:growth','growth','legacy_v4',3,249900,'{"jobs":15,"users":5,"storage":50000000000,"video":5}');UPDATE gethired.companies_subscription SET plan_slug='growth',subscription_id=3,is_paid=TRUE,sub_status='active',billing_plan_version_id='legacy:growth',agreed_monthly_minor=249900,effective_entitlements='{"jobs":15,"users":5,"storage":50000000000,"video":5}',period_end='2026-10-01' WHERE company_id='a';`);const input={planCode:'growth',operation:'renewal',idempotencyKey:'renewal_001'};let a=await f.s.checkout(f.c,input);assert.equal(a.amountMinor,249900);await f.s.webhook(...f.signed(f.event(a)));assert.equal((await f.s.checkout(f.c,input)).paymentAttemptId,a.paymentAttemptId);assert.equal((await f.s.effective(f.c)).planVersionId,'legacy:growth');await f.pg.exec("UPDATE gethired.billing_plan_versions SET annual_minor=6000000 WHERE id='pricing_2026_09:premium'");a=await f.s.checkout(f.c,{planCode:'premium',billingCycle:'annual'});assert.equal(a.amountMinor,6000000);await f.s.webhook(...f.signed(f.event(a)));assert.equal((await f.s.effective(f.c)).billingCycle,'annual');}finally{await f.close();}});
test('provider mock receives centavos once and colon-only Basic auth; calendar term clamps days',async()=>{const key='sk_test_'+crypto.randomBytes(32).toString('hex');const config={catalogVersion:'pricing_2026_09',enabled:true,mode:'test',nodeEnv:'test',dbHost:'localhost',secretKey:key};const p=provider({post:async(url,body,opt)=>{assert.equal(body.data.attributes.amount,129000);assert.equal(Buffer.from(opt.headers.Authorization.slice(6),'base64').toString(),key+':');assert.equal(url,'https://api.paymongo.com/v1/links');return {data:{data:{id:'link_mock',attributes:{amount:129000,currency:'PHP',livemode:false,checkout_url:'https://pm.link/mock'}}}};}},config);await p.createLink({expected_amount_minor:129000,internal_reference:'GH_PAY_'+crypto.randomBytes(16).toString('hex')});assert.equal(termEnd(new Date('2024-02-29T00:00:00Z'),'annual').toISOString(),'2025-02-28T00:00:00.000Z');assert.equal(termEnd(new Date('2026-01-31T00:00:00Z'),'monthly').toISOString(),'2026-02-28T00:00:00.000Z');});
test('legacy link event, payment event and concurrent duplicate finalize one receipt; reconciliation runs identical finalizer',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'starter'});const attempt=f.last();const payment=f.event(a).data.attributes.data;const resource={id:'link_'+attempt.id,type:'link',attributes:{amount:a.amountMinor,currency:'PHP',livemode:false,status:'paid',remarks:attempt.internal_reference,reference_number:'ref_'+attempt.id,payments:[{data:payment}]}};const e={data:{id:'evt_link'+attempt.id,type:'event',attributes:{type:'link.payment.paid',livemode:false,data:resource}}};const results=await Promise.all([f.s.webhook(...f.signed(e)),f.s.webhook(...f.signed(e)),f.s.webhook(...f.signed(f.event(a)))]);assert.equal(results.filter(x=>x.status==='PROCESSED').length,1);assert.equal(await count(f.pg,'invoices'),1);f.setResource(resource);assert.equal((await f.s.reconcile(a.paymentAttemptId,{authorized:true,uid:'operator'})).status,'DUPLICATE');assert.equal(await count(f.pg,'invoices'),1);await assert.rejects(()=>f.s.reconcile(a.paymentAttemptId,{authorized:false}),{httpStatus:403});}finally{await f.close();}});
test('approved Enterprise order owns custom price and caps; unapproved or other account order fails closed',async()=>{const f=await setup();try{await f.pg.exec(`INSERT INTO gethired.billing_approved_orders(id,company_id,plan_version_id,amount_minor,billing_cycle,custom_entitlements,approved_by,approved_at,expires_at) VALUES('order_a','a','pricing_2026_09:enterprise',1234500,'monthly','{"jobs":100,"users":50,"storage":900000000000,"video":20}','operator','2026-09-01','2026-10-01'),('order_b','b','pricing_2026_09:enterprise',500000,'monthly','{"jobs":50,"users":20,"storage":500000000000,"video":10}','operator','2026-09-01','2026-10-01');`);await assert.rejects(()=>f.s.checkout(f.c,{planCode:'enterprise',enterpriseOrderId:'order_b'}),{code:'ENTERPRISE_ORDER_NOT_APPROVED'});const a=await f.s.checkout(f.c,{planCode:'enterprise',enterpriseOrderId:'order_a'});assert.equal(a.amountMinor,1234500);await f.s.webhook(...f.signed(f.event(a)));assert.equal((await f.s.effective(f.c)).entitlements.storage,900000000000);assert.equal((await f.s.effective(f.c)).planCode,'enterprise');assert.equal((await f.pg.query("SELECT status FROM gethired.billing_approved_orders WHERE id='order_a'")).rows[0].status,'PAID');}finally{await f.close();}});
test('expired paid attempt and missing ledger fail closed; same event identity cannot mutate its payload',async()=>{const f=await setup();try{const a=await f.s.checkout(f.c,{planCode:'starter'});const e=f.event(a);await f.pg.query("UPDATE gethired.payment_attempts SET expires_at='2026-09-12' WHERE id=$1",[a.paymentAttemptId]);assert.equal((await f.s.webhook(...f.signed(e))).code,'PAYMENT_ATTEMPT_EXPIRED');e.data.attributes.data.attributes.amount++;await assert.rejects(()=>f.s.webhook(...f.signed(e)),{code:'PAYMONGO_EVENT_ID_CONFLICT'});assert.equal(await count(f.pg,'payment_transactions'),0);await f.pg.exec('DROP TABLE gethired.payment_webhook_events');await assert.rejects(()=>f.s.webhook(...f.signed(f.event(a))));assert.equal(await count(f.pg,'payment_transactions'),0);}finally{await f.close();}});
test('HTTP raw webhook and owner routes support pending then paid; reject recruiter, candidate, price injection and cross account status',async()=>{const f=await setup();const express=require('express');const {routes,webhook}=require('../services/paymongo-billing/http.cjs');const app=express();app.post('/api/payment/paymongowebhook',express.raw({type:'application/json',limit:'256kb'}),webhook(f.s));app.use(express.json());const auth=(req,res,next)=>{if(!req.headers['test-uid'])return res.status(401).json({code:'AUTH_REQUIRED'});req.user={uid:req.headers['test-uid']};next();};app.use('/api',routes(express,f.s,auth));const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.on('listening',r));const base='http://127.0.0.1:'+server.address().port+'/api';const request=(path,uid='owner',body)=>fetch(base+path,{method:body?'POST':'GET',headers:{'test-uid':uid,'content-type':'application/json'},body:body?JSON.stringify(body):undefined});try{let res=await request('/employer/subscription/checkout','owner',{planCode:'growth'});assert.equal(res.status,200);const a=await res.json();assert.equal((await(await request('/employer/subscription/checkout/'+a.paymentAttemptId+'/status')).json()).status,'PENDING');assert.equal((await request('/employer/subscription/checkout/'+a.paymentAttemptId+'/status','other')).status,404);for(const uid of ['recruiter','candidate'])assert.equal((await request('/employer/subscription/checkout',uid,{planCode:'growth'})).status,403);assert.equal((await request('/employer/subscription/checkout','owner',{planCode:'growth',amount:1})).status,400);const [raw,h]=f.signed(f.event(a));res=await fetch(base+'/payment/paymongowebhook',{method:'POST',headers:{'content-type':'application/json','paymongo-signature':h},body:raw});assert.equal(res.status,200);assert.equal((await(await request('/employer/subscription/checkout/'+a.paymentAttemptId+'/status')).json()).status,'PAID');res=await fetch(base+'/payment/paymongowebhook',{method:'POST',headers:{'content-type':'application/json'},body:raw});assert.equal(res.status,400);}finally{await new Promise(r=>server.close(r));await f.close();}});
test('paid domain event feeds shared engagement worker and one addon confirmation without renewal labeling',async()=>{const f=await setup();try{const {repository}=require('../services/subscription-engagement/repository.cjs');const engagement=repository(f.pg,'gethired');let a=await f.s.checkout(f.c,{planCode:'growth'});await f.s.webhook(...f.signed(f.event(a)));while(await engagement.processNext()){}a=await f.s.checkout(f.c,{packageCode:'storage_25'});await f.s.webhook(...f.signed(f.event(a)));while(await engagement.processNext()){}const rows=await f.pg.query("SELECT template_key FROM gethired.notifications WHERE company_id='a' AND template_key='billing.storage_addon_activated'");assert.equal(rows.rows.length,1);assert.equal((await f.pg.query("SELECT snapshot FROM gethired.engagement_accounts WHERE company_id='a'")).rows[0].snapshot.effectiveLimits.storage,75000000000);assert.equal((await f.pg.query("SELECT COUNT(*)::int AS n FROM gethired.engagement_events WHERE type='SUBSCRIPTION_RENEWED'")).rows[0].n,0);}finally{await f.close();}});
test('legacy backfill reports unmapped accounts and applies only explicit approved agreements atomically',async()=>{const f=await setup();try{const {backfill}=require('../services/paymongo-billing/legacy-backfill.cjs');await f.pg.exec(`CREATE TABLE gethired.cart_table(cart_id varchar,company_id varchar,subscription_id int,price numeric,status varchar,created_at timestamptz,transaction_id varchar);UPDATE gethired.companies_subscription SET subscription_id=3,plan_slug='growth',is_paid=TRUE,sub_status='active' WHERE company_id='a';INSERT INTO gethired.cart_table VALUES('legacy_cart','a',3,2499,'pending',NOW(),NULL);`);const svc=backfill(f.pg,'gethired');let report=await svc.report();assert.equal(report.agreements[0].status,'NEEDS_APPROVED_AGREEMENT');assert.equal(report.pendingCarts[0].status,'NEEDS_PROVIDER_REFERENCE_REVIEW');const manifest={version:1,agreements:[{companyId:'a',planCode:'growth',billingCycle:'monthly',monthlyMinor:249900,periodStart:'2026-09-01T00:00:00Z',periodEnd:'2026-10-01T00:00:00Z',entitlements:{jobs:15,users:5,storage:50000000000,video:5}}]};assert.deepEqual(await svc.apply(manifest,'reviewer'),{mapped:1});assert.deepEqual(await svc.apply(manifest,'reviewer'),{mapped:0});report=await svc.report();assert.equal(report.agreements[0].status,'MAPPED');assert.equal((await f.s.effective(f.c)).entitlements.storage,50000000000);await assert.rejects(()=>svc.apply({version:1,agreements:[{...manifest.agreements[0],monthlyMinor:null}]},'reviewer'),{code:'BACKFILL_MANIFEST_INVALID'});}finally{await f.close();}});

test('current catalog preserves published monthly and annual prices and entitlements',async()=>{
 const f=await setup();try{
  delete f.config.catalogVersion;
  for(const [plan,monthly,annual,jobs,users] of [['starter',149000,1490000,2,1],['growth',349000,3490000,6,3],['premium',599000,5990000,40,15]]){
   const p=(await f.pg.query('SELECT * FROM gethired.billing_plan_versions WHERE id=$1',['pricing_2026_09_21:'+plan])).rows[0];
   assert.equal(Number(p.monthly_minor),monthly);assert.equal(Number(p.annual_minor),annual);assert.equal(p.entitlements.jobs,jobs);assert.equal(p.entitlements.users,users);
  }
  const a=await f.s.checkout(f.c,{planCode:'growth',billingCycle:'annual'});assert.equal(a.amountMinor,3490000);
  await f.s.webhook(...f.signed(f.event(a)));assert.equal((await f.s.effective(f.c)).entitlements.jobs,6);
  assert.equal((await f.pg.query('SELECT plan_version_id FROM gethired.payment_attempts')).rows[0].plan_version_id,'pricing_2026_09_21:growth');
 }finally{await f.close();}
});
test('new trial is unpaid and idempotent and cannot grant a paid subscription',async()=>{
 const f=await setup();try{
  const {provision}=require('../services/paymongo-billing/trial.cjs');
  const trial=await provision(f.pg,'gethired','b',1);assert.equal(trial.is_paid,false);assert.equal(trial.payment_date,null);assert.equal(+new Date(trial.period_end)-+new Date(trial.period_start),7*86400000);
  await provision(f.pg,'gethired','b',1);assert.equal((await f.pg.query("SELECT COUNT(*)::int AS n FROM gethired.companies_subscription WHERE company_id='b'")).rows[0].n,1);
  await assert.rejects(()=>provision(f.pg,'gethired','b',2),{code:'PAYMENT_REQUIRED'});
 }finally{await f.close();}
});
test('unverified legacy paid flags require reconciliation before any charge',async()=>{
 const f=await setup();try{
  await f.pg.query("UPDATE gethired.companies_subscription SET is_paid=TRUE WHERE company_id='a'");
  await assert.rejects(()=>f.s.checkout(f.c,{planCode:'growth'}),{code:'BILLING_AGREEMENT_REQUIRED'});
  assert.equal(f.calls(),0);assert.equal(await count(f.pg,'payment_attempts'),0);
 }finally{await f.close();}
});
