const {test}=require('node:test');const assert=require('node:assert/strict');const crypto=require('node:crypto');const fs=require('node:fs');
const {setup}=require('./support/referral-payment-fixture.cjs');const {refundIntake,refunds,proportional}=require('../services/referral-bunny/refunds.cjs');
async function fixture(){const f=await setup();await f.pg.exec(fs.readFileSync('db/referral_bunny_refunds_migration.sql','utf8'));await f.pg.exec(fs.readFileSync('db/referral_bunny_refunds_migration.sql','utf8'));f.config.refundsEnabled=true;
 const intake=refundIntake(f.pg,'gethired',{enabled:true,mode:'live',webhookSecret:'secret'});let broken=false;const reversals=[];
 f.refunds=refunds(f.pg,'gethired',{paymentContext:async()=>f.context},f.config,async(url,body,h)=>{assert.equal(h['X-RB-Signature'],crypto.createHmac('sha256',f.context.secret).update(h['X-RB-Timestamp']+'.'+body).digest('hex'));reversals.push(body);if(broken)throw Error('lost response');return {received:true};});
 f.broken=x=>broken=x;f.reversals=reversals;
 f.event=(id,amount,extra={})=>({data:{id:'evt_'+id,type:'event',attributes:{type:'refund.succeeded',livemode:true,data:{id:'ref_'+id,type:'refund',attributes:{status:'succeeded',payment_id:'pay_1',amount,currency:'PHP',livemode:true,created_at:1788480000,...extra}}}}});
 f.receive=async(event,bad=false)=>{const raw=Buffer.from(JSON.stringify(event)),t=String(Math.floor(Date.now()/1000));const sig=crypto.createHmac('sha256',bad?'bad':'secret').update(t+'.').update(raw).digest('hex');return intake.webhook(raw,'t='+t+',li='+sig);};
 f.original=async()=>{await f.invoice(1);await f.pg.exec("UPDATE payment_transactions SET provider_payment_id='pay_1';UPDATE payment_attempts SET paymongo_payment_id='pay_1';UPDATE payment_webhook_events SET provider_payment_id='pay_1';UPDATE invoices SET transaction_id='pay_1';");await f.service.prepare();};return f;
}
test('verified partial then full refund allocate tax proportionally and retry exact reversal once',async()=>{const f=await fixture();try{await f.original();await f.service.deliverNext();await f.receive(f.event('a',33600));await f.receive(f.event('b',67200));assert.deepEqual(await f.refunds.prepare(),{queued:2,held:0});f.broken(true);assert.equal((await f.refunds.deliverNext()).delivered,false);assert.equal((await f.refunds.deliverNext()).processed,false);await f.pg.exec("UPDATE referral_bunny_refunds SET next_attempt_at=NOW()-INTERVAL '1 second'");f.broken(false);await f.refunds.deliverNext();await f.refunds.deliverNext();assert.equal(f.reversals[0],f.reversals[1]);assert.deepEqual(f.reversals.slice(1).map(x=>JSON.parse(x).amount_minor),[30000,60000]);assert.equal((await f.refunds.deliverNext()).processed,false);}finally{await f.pg.close();}});
test('refund arriving before its payment waits and blocks original until reversal is staged',async()=>{const f=await fixture();try{await f.receive(f.event('early',100800));assert.deepEqual(await f.refunds.prepare(),{queued:0,held:0});await f.original();assert.equal((await f.service.deliverNext()).reason,'REFUND_NOT_PREPARED');await f.refunds.prepare();assert.equal((await f.refunds.deliverNext()).processed,false);await f.service.deliverNext();assert.equal((await f.refunds.deliverNext()).delivered,true);assert.equal(JSON.parse(f.reversals[0]).amount_minor,90000);}finally{await f.pg.close();}});
test('signature, mode and immutable refund identity are enforced; pending and failed do not reverse',async()=>{const f=await fixture();try{await assert.rejects(()=>f.receive(f.event('a',10),true),{code:'PAYMONGO_WEBHOOK_INVALID'});const mode=f.event('mode',10);mode.data.attributes.livemode=false;await assert.rejects(()=>f.receive(mode),{code:'PAYMONGO_MODE_MISMATCH'});await f.receive(f.event('pending',10,{status:'pending'}));await f.receive(f.event('failed',10,{status:'failed'}));const e=f.event('a',10);await f.receive(e);assert.equal((await f.receive(e)).duplicate,true);e.data.id='evt_repeat';await f.receive(e);e.data.id='evt_conflict';e.data.attributes.data.attributes.amount=11;await assert.rejects(()=>f.receive(e),{code:'REFUND_ID_CONFLICT'});assert.equal((await f.pg.query('SELECT COUNT(*)::int AS n FROM referral_bunny_provider_refunds')).rows[0].n,1);}finally{await f.pg.close();}});
test('over-refunds are held and disconnect prevents transmission',async()=>{const f=await fixture();try{await f.original();await f.service.deliverNext();await f.receive(f.event('over',100801));assert.equal((await f.refunds.prepare()).held,1);assert.equal((await f.refunds.deliverNext()).processed,false);await f.pg.exec('UPDATE referral_bunny_platform SET disconnected_at=NOW()');await assert.rejects(()=>f.refunds.deliverNext(),{code:'CONNECTION_CHANGED'});assert.equal(f.reversals.length,0);}finally{await f.pg.close();}});
test('cumulative rounding reaches exactly original net and zero-net adjustments stay local',async()=>{assert.equal(proportional(1,3,1),0);assert.equal(proportional(1,3,2),1);assert.equal(proportional(1,3,3),1);assert.throws(()=>proportional(1,3,4));const f=await fixture();try{await f.original();await f.service.deliverNext();await f.pg.exec(`UPDATE referral_bunny_payments SET gross_minor=3,payload=jsonb_set(payload::jsonb,'{amount_minor}','1')::text`);await f.receive(f.event('tiny',1));await f.refunds.prepare();assert.equal((await f.refunds.deliverNext()).delivered,true);assert.equal(f.reversals.length,0);}finally{await f.pg.close();}});
