/**
 * Role Template Library V4
 * Deterministic content banks per role family — no external AI.
 * SYNTAX: no ?. or ?? — Node 14 ESM safe.
 *
 * Each template provides banks of content items.
 * The generator selects and varies items — never invents facts.
 */

// ── Template shape ─────────────────────────────────────────────────────────────
// {
//   id, label, responsibilitiesBank[], requiredQualificationsBank[],
//   preferredQualificationsBank[], skills[], tools[],
//   interviewQuestionBank[], videoPromptBank[],
//   badgeSuggestionRules[], educationNote, experienceNote,
//   fakeClaims[], variationProfiles[]
// }

var TEMPLATES = {

  // ── Events / Field Activation ────────────────────────────────────────────────
  events_field_activation: {
    id: 'events_field_activation',
    label: 'Events / Field Activation',
    responsibilitiesBank: [
      'Plan and manage end-to-end events, trainings, demos, roadshows, launches, and stakeholder activations.',
      'Build event timelines, run-of-show documents, logistics checklists, staffing plans, and production schedules.',
      'Coordinate vendors, venues, suppliers, speakers, partners, and internal teams.',
      'Manage budgets, supplier coordination, procurement requests, and post-event reconciliation where applicable.',
      'Lead onsite execution and resolve operational issues before, during, and after events.',
      'Work with sales, marketing, product, client success, and leadership teams to align events with business or rollout objectives.',
      'Prepare event briefs, attendance reports, post-event summaries, feedback notes, and improvement recommendations.',
      'Maintain reusable event templates, supplier lists, playbooks, and planning tools.',
      'Support stakeholder communications before and after events.',
      'Ensure event materials, presentations, demos, signage, and support resources are prepared on time.',
      'Track event KPIs such as attendance, engagement, leads generated, and satisfaction scores.',
      'Manage event staff, agency partners, and volunteer coordinators.',
    ],
    requiredQualificationsBank: [
      'Experience managing events, trainings, product demos, roadshows, conferences, or field activations.',
      'Strong project management and logistics coordination skills.',
      'Experience coordinating vendors, venues, budgets, timelines, and event teams.',
      'Strong communication and stakeholder-management skills.',
      'Ability to manage multiple events or workstreams at the same time.',
      'Comfortable using spreadsheets, presentation tools, project trackers, or event planning tools.',
      'Strong onsite problem-solving and decision-making skills.',
      'Ability to prepare clear reports, briefs, and post-event documentation.',
    ],
    preferredQualificationsBank: [
      'Experience with government, LGU, civic-tech, SaaS, training, education, or public-sector events.',
      'Experience running product demos, workshops, client trainings, or community/stakeholder activations.',
      'Experience producing post-event reports and measuring attendance, engagement, leads, or rollout outcomes.',
      'Experience managing event staff, agencies, suppliers, or external partners.',
      'Experience working with cross-functional teams such as sales, marketing, product, and client success.',
    ],
    skills: ['event planning', 'field activation', 'logistics coordination', 'vendor management', 'budget tracking', 'stakeholder management', 'run-of-show planning', 'onsite operations', 'project management', 'communication', 'reporting', 'supplier coordination'],
    tools: ['Google Workspace', 'Airtable', 'Trello', 'Asana', 'MS Excel', 'PowerPoint', 'Canva'],
    interviewQuestionBank: [
      'Tell us about an event you managed from planning to post-event reporting. What was your role and what changed because of the event?',
      'How do you handle last-minute vendor, venue, or schedule changes during an event?',
      'Describe how you would plan a product demo or training event for stakeholders.',
      'What event metrics do you track after an event, and how do you use them to improve the next one?',
      'How do you coordinate internal teams, suppliers, and stakeholders when priorities change?',
      'Walk us through how you manage an event timeline and keep stakeholders updated.',
    ],
    videoPromptBank: [
      'Walk us through one event you are proud of and the result you achieved.',
      'How would you prepare for a high-stakes stakeholder event with limited time?',
      'Explain your approach to coordinating vendors, internal teams, and client stakeholders.',
    ],
    badgeSuggestionRules: [
      { badge: 'Events & Field Exposure', condition: 'always' },
      { badge: 'Mission-Driven', condition: 'if civic/LGU/public-sector context' },
      { badge: 'Salary Posted', condition: 'if salary supplied' },
      { badge: 'Benefits Included', condition: 'if benefits supplied' },
    ],
    educationNote: 'Do not require a specific degree unless employer supplies it.',
    experienceNote: 'Experience in events or coordination; years based on seniority.',
    fakeClaims: ['salary', 'benefits', 'travel allowance', 'government client names', 'official partnerships', 'exact event frequency'],
    variationProfiles: ['standard_candidate_friendly', 'senior_operations_leadership', 'field_activation_civic_tech'],
  },

  // ── Finance / Accounting ─────────────────────────────────────────────────────
  finance_accounting: {
    id: 'finance_accounting',
    label: 'Finance / Accounting',
    responsibilitiesBank: [
      'Prepare financial reports, dashboards, variance analyses, and budget summaries.',
      'Review revenue, cost, expense, and operational data for accuracy and trends.',
      'Support budgeting, forecasting, and monthly/quarterly reporting cycles.',
      'Reconcile financial data across spreadsheets, accounting systems, or internal reports.',
      'Prepare analysis to support management decisions and business planning.',
      'Coordinate with accounting, operations, sales, or management teams to validate financial assumptions.',
      'Maintain organized documentation for reports, assumptions, and supporting schedules.',
      'Identify unusual movements, data inconsistencies, or opportunities for cost control.',
      'Assist in audit preparation and coordinate with internal or external auditors as needed.',
      'Process invoices, accounts payable, or accounts receivable based on role scope.',
    ],
    requiredQualificationsBank: [
      'Experience in finance, accounting, business analysis, or reporting.',
      'Strong spreadsheet and data analysis skills.',
      'Understanding of financial statements, budgets, forecasts, or variance analysis.',
      'Attention to detail and ability to validate numbers.',
      'Clear communication skills for explaining financial insights.',
      'Ability to meet reporting deadlines and manage multiple deliverables.',
    ],
    preferredQualificationsBank: [
      'Experience with accounting systems such as SAP, Oracle, QuickBooks, or similar.',
      'Experience supporting audit preparation or external reporting.',
      'CPA license or in progress — mark as review if inferred, not required unless stated.',
      'Experience in budgeting, forecasting, or financial modeling.',
      'Exposure to ERP systems or financial dashboards.',
    ],
    skills: ['financial reporting', 'data analysis', 'reconciliation', 'budgeting', 'forecasting', 'variance analysis', 'attention to detail', 'spreadsheet proficiency'],
    tools: ['Microsoft Excel', 'Google Sheets', 'SAP', 'QuickBooks', 'Xero', 'Oracle', 'Power BI'],
    interviewQuestionBank: [
      'Walk us through your experience preparing financial reports or analyses.',
      'Describe a situation where you found and resolved a discrepancy in financial data.',
      'How do you prioritize competing deadlines during a reporting cycle?',
      'What accounting tools or systems have you used, and how did you use them?',
      'How do you explain complex financial data to non-finance stakeholders?',
    ],
    videoPromptBank: [
      'Describe a financial report or analysis you are proud of and why it was valuable.',
      'How do you approach a reconciliation task when the numbers do not match?',
      'How would you help a team understand budget vs actuals?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
      { badge: 'Benefits Included', condition: 'if benefits supplied' },
    ],
    educationNote: 'Bachelor\'s degree in finance/accounting/business — mark for review if inferred; only require if employer states.',
    experienceNote: 'Experience in finance or accounting; CPA not required unless supplied.',
    fakeClaims: ['salary', 'specific accounting software', 'CPA requirement', 'company financial data'],
    variationProfiles: ['standard_candidate_friendly', 'finance_reporting_analysis'],
  },

  // ── Customer Service / BPO ───────────────────────────────────────────────────
  customer_service_bpo: {
    id: 'customer_service_bpo',
    label: 'Customer Service / BPO',
    responsibilitiesBank: [
      'Handle customer inquiries through phone, chat, email, or ticketing channels.',
      'Provide accurate information about products, services, accounts, or processes.',
      'Document customer interactions and update records in the CRM or ticketing system.',
      'Resolve issues within service standards or escalate when needed.',
      'Follow scripts, quality guidelines, and data privacy procedures.',
      'Coordinate with internal teams for unresolved concerns.',
      'Meet service level agreements and quality metrics.',
      'Identify opportunities to improve the customer experience and report trends.',
    ],
    requiredQualificationsBank: [
      'Clear and effective communication skills in English.',
      'Customer service mindset with a focus on empathy and resolution.',
      'Basic computer skills and ability to navigate digital tools.',
      'Ability to follow procedures and document interactions accurately.',
    ],
    preferredQualificationsBank: [
      'Experience in BPO, customer service, or call center environments preferred.',
      'Experience with CRM tools such as Salesforce, Zendesk, or Freshdesk.',
      'Experience handling specific account types relevant to this role.',
      'Technical support experience for relevant products or services.',
    ],
    skills: ['communication', 'customer handling', 'issue resolution', 'active listening', 'documentation', 'empathy', 'CRM usage', 'process adherence'],
    tools: ['Zendesk', 'Salesforce', 'Freshdesk', 'Intercom', 'Slack', 'Email platforms'],
    interviewQuestionBank: [
      'Tell us about a time you handled a difficult or frustrated customer. What did you do and what was the outcome?',
      'How do you stay organized and accurate when handling a high volume of customer interactions?',
      'Describe how you would handle a customer escalation that you cannot resolve on your own.',
      'How do you ensure every customer interaction is documented correctly?',
    ],
    videoPromptBank: [
      'Walk us through how you handle a customer complaint from start to resolution.',
      'Describe a moment when you turned a negative customer experience into a positive one.',
      'How would you handle back-to-back difficult calls or chats in a single shift?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
      { badge: 'Benefits Included', condition: 'if benefits supplied' },
    ],
    educationNote: 'No specific degree required unless employer states.',
    experienceNote: 'Prior customer service experience preferred but not required unless employer states.',
    fakeClaims: ['graveyard shift', 'specific account type', 'salary', 'benefits', 'exact shift schedule'],
    variationProfiles: ['standard_candidate_friendly', 'customer_service_bpo'],
  },

  // ── IT / Software / Data ──────────────────────────────────────────────────────
  it_software_data: {
    id: 'it_software_data',
    label: 'IT / Software / Data',
    responsibilitiesBank: [
      'Build and maintain application features, APIs, or system integrations.',
      'Write clean, maintainable, and tested code following established coding standards.',
      'Debug and resolve issues in development, staging, or production environments.',
      'Collaborate with product managers, designers, and QA engineers on feature development.',
      'Participate in code reviews, sprint planning, and technical design discussions.',
      'Document technical decisions, system architecture, and code changes.',
      'Support deployments, releases, and post-deployment monitoring.',
      'Identify and implement performance improvements and technical debt reduction.',
      'Manage databases, data pipelines, or infrastructure components as applicable.',
      'Research and evaluate new tools and technologies relevant to the team\'s stack.',
    ],
    requiredQualificationsBank: [
      'Programming experience in relevant languages or frameworks.',
      'Understanding of software development best practices and version control.',
      'Ability to debug and solve technical problems independently.',
      'Experience with RESTful APIs, databases, or frontend/backend components.',
      'Strong problem-solving and analytical skills.',
      'Ability to communicate technical concepts clearly to non-technical teammates.',
    ],
    preferredQualificationsBank: [
      'Experience with the specific tech stack used in this role.',
      'Experience with cloud platforms such as AWS, GCP, or Azure.',
      'Experience with containerization tools such as Docker or Kubernetes.',
      'Experience in agile or scrum development environments.',
      'Open source contributions or portfolio projects.',
    ],
    skills: ['programming', 'debugging', 'system design', 'API development', 'database management', 'code review', 'version control', 'testing'],
    tools: ['Git', 'GitHub', 'Docker', 'Postman', 'VS Code', 'Jira', 'Confluence'],
    interviewQuestionBank: [
      'Walk us through a feature or project you built from design to deployment.',
      'Describe a bug you had to debug that took longer than expected. What was the process?',
      'How do you approach writing code that will be maintained by other engineers?',
      'Describe your experience with the technologies listed for this role.',
      'How do you prioritize technical debt alongside feature development?',
    ],
    videoPromptBank: [
      'Walk us through a technical project you built and what problem it solved.',
      'How do you approach learning a new technology or framework on the job?',
      'Describe how you collaborate with non-technical teammates on a product feature.',
    ],
    badgeSuggestionRules: [
      { badge: 'Remote-Friendly', condition: 'if workSetup is remote or hybrid' },
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No degree requirement unless employer states; portfolio/skills-based evaluation preferred.',
    experienceNote: 'Experience with relevant stack; years based on seniority level.',
    fakeClaims: ['specific tech stack requirement unless supplied', 'salary', 'AI/ML requirement', 'years of experience beyond seniority'],
    variationProfiles: ['technical_delivery'],
  },

  // ── HR / Recruitment ──────────────────────────────────────────────────────────
  hr_recruitment: {
    id: 'hr_recruitment',
    label: 'HR / Recruitment',
    responsibilitiesBank: [
      'Source, screen, and evaluate candidates through job boards, referrals, and direct outreach.',
      'Coordinate and schedule interviews with candidates and hiring managers.',
      'Manage end-to-end recruitment processes from job posting to offer release.',
      'Maintain accurate candidate records and ATS data.',
      'Support employee onboarding, documentation, and orientation programs.',
      'Handle HR administrative tasks including leave tracking, payroll coordination, and record keeping.',
      'Assist in implementing HR policies, employee handbook updates, and compliance requirements.',
      'Coordinate with department heads on headcount planning and talent requirements.',
      'Support learning and development programs, performance reviews, and employee engagement initiatives.',
      'Handle employee relations concerns and coordinate with management for resolution.',
    ],
    requiredQualificationsBank: [
      'Experience in recruitment, talent acquisition, or HR generalist functions.',
      'Strong interviewing, sourcing, and candidate management skills.',
      'Experience using ATS platforms or HR management systems.',
      'Clear communication skills for candidate and stakeholder engagement.',
      'Strong organizational and documentation skills.',
      'Ability to manage confidential employee information with discretion.',
    ],
    preferredQualificationsBank: [
      'Experience in high-volume recruitment or specialized technical hiring.',
      'Experience with HRIS platforms such as Workday, BambooHR, or SAP HR.',
      'Experience supporting HR operations, compliance, or labor relations.',
      'Experience conducting behavioral or competency-based interviews.',
    ],
    skills: ['sourcing', 'screening', 'interviewing', 'ATS management', 'onboarding', 'documentation', 'communication', 'confidentiality'],
    tools: ['LinkedIn Recruiter', 'Workday', 'BambooHR', 'Greenhouse', 'Lever', 'Google Workspace'],
    interviewQuestionBank: [
      'Walk us through your typical end-to-end recruitment process from requisition to offer.',
      'How do you source candidates for hard-to-fill roles?',
      'Describe a time when you had to manage multiple open roles simultaneously.',
      'How do you ensure a positive candidate experience even for applicants who are not selected?',
    ],
    videoPromptBank: [
      'Walk us through a successful placement you are proud of.',
      'How do you evaluate a candidate\'s culture fit without relying on subjective judgments?',
      'Describe a challenging hiring situation and how you resolved it.',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
      { badge: 'Benefits Included', condition: 'if benefits supplied' },
    ],
    educationNote: 'No specific degree required unless employer states.',
    experienceNote: 'Recruitment or HR experience; years based on seniority.',
    fakeClaims: ['salary', 'specific HRIS requirement', 'industry-specific hiring volume claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },

  // ── Government / LGU / Civic Technology ─────────────────────────────────────
  lgu_civic_technology: {
    id: 'lgu_civic_technology',
    label: 'Government / LGU / Civic Technology',
    responsibilitiesBank: [
      'Coordinate project tasks, timelines, meetings, and documentation for LGU or civic technology initiatives.',
      'Support client or stakeholder communication and follow-ups.',
      'Track action items, dependencies, and implementation progress.',
      'Prepare reports, meeting notes, rollout materials, and status updates.',
      'Support trainings, demos, and onboarding sessions for LGU clients or users.',
      'Coordinate with product, technical, and operations teams on deliverables.',
      'Maintain organized records of project documentation, correspondence, and approvals.',
      'Assist in the preparation of presentations, proposals, and briefing materials.',
    ],
    requiredQualificationsBank: [
      'Project coordination or operations experience.',
      'Strong organization and documentation skills.',
      'Stakeholder communication skills.',
      'Ability to manage follow-ups and timelines.',
      'Comfortable with spreadsheets, documents, and project trackers.',
    ],
    preferredQualificationsBank: [
      'Experience working with government, LGU, or public-sector clients or partners.',
      'Experience supporting digital transformation or technology rollout programs.',
      'Familiarity with government procurement or documentation processes.',
      'Experience coordinating training sessions or stakeholder workshops.',
    ],
    skills: ['stakeholder coordination', 'documentation', 'project tracking', 'communication', 'scheduling', 'reporting', 'follow-through'],
    tools: ['Google Workspace', 'Microsoft Office', 'Trello', 'Notion', 'Zoom', 'Airtable'],
    interviewQuestionBank: [
      'Describe a project where you had to coordinate multiple stakeholders with competing priorities.',
      'How do you ensure follow-through on action items from a meeting with government or client counterparts?',
      'Tell us about a time you prepared documentation or a report for a government or public-sector audience.',
      'How do you handle changes in scope or direction mid-project?',
    ],
    videoPromptBank: [
      'Walk us through a coordination challenge you resolved effectively.',
      'How would you keep a complex multi-stakeholder project on track?',
      'Describe your approach to preparing for a client or government meeting.',
    ],
    badgeSuggestionRules: [
      { badge: 'Mission-Driven', condition: 'if civic/LGU/public-sector context confirmed' },
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No specific degree required unless employer states.',
    experienceNote: 'Coordination or project support experience relevant to the role.',
    fakeClaims: ['government authority', 'official LGU designation', 'specific municipal client names', 'travel requirements', 'legal compliance role'],
    variationProfiles: ['standard_candidate_friendly', 'field_activation_civic_tech'],
  },

  // ── Administration / Office ──────────────────────────────────────────────────
  administration_office: {
    id: 'administration_office',
    label: 'Administration / Office',
    responsibilitiesBank: [
      'Provide administrative and clerical support to teams, departments, or leadership.',
      'Manage scheduling, calendar coordination, meeting preparation, and follow-ups.',
      'Prepare and manage documents, reports, correspondence, and filing systems.',
      'Handle data entry, encoding, and maintenance of internal databases or records.',
      'Coordinate with internal departments for operational and administrative needs.',
      'Process requests, approvals, purchase orders, or expense reports as applicable.',
      'Maintain office supplies, equipment, and vendor coordination.',
      'Support onboarding of new staff with documentation and orientation logistics.',
    ],
    requiredQualificationsBank: [
      'Administrative support experience in an office environment.',
      'Strong organizational and multi-tasking skills.',
      'Proficiency in Microsoft Office or Google Workspace.',
      'Attention to detail and accuracy in data entry and documentation.',
      'Clear communication skills (written and verbal).',
    ],
    preferredQualificationsBank: [
      'Experience providing executive-level administrative support.',
      'Experience with document management or records systems.',
      'Experience in a fast-paced or multi-department environment.',
    ],
    skills: ['organization', 'scheduling', 'documentation', 'data entry', 'communication', 'file management', 'multi-tasking'],
    tools: ['Microsoft Office', 'Google Workspace', 'Zoom', 'Slack', 'Trello', 'email platforms'],
    interviewQuestionBank: [
      'Describe how you manage competing priorities and deadlines in a busy admin role.',
      'How do you ensure accuracy when handling large volumes of documents or data?',
      'Tell us about a process you improved in a previous administrative role.',
    ],
    videoPromptBank: [
      'Walk us through a typical busy day in your current or previous admin role.',
      'How do you prioritize when you have multiple urgent tasks from different managers?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No degree requirement unless employer states.',
    experienceNote: 'Administrative experience; specific software skills preferred.',
    fakeClaims: ['salary', 'specific software requirement', 'company-specific admin processes'],
    variationProfiles: ['standard_candidate_friendly'],
  },

  // ── Sales / Business Development ─────────────────────────────────────────────
  sales_business_dev: {
    id: 'sales_business_dev',
    label: 'Sales / Business Development',
    responsibilitiesBank: [
      'Prospect, qualify, and develop new business opportunities and client relationships.',
      'Manage the full sales cycle from lead generation to close.',
      'Meet or exceed individual or team sales targets and revenue goals.',
      'Build and maintain long-term relationships with clients, prospects, and partners.',
      'Prepare sales proposals, presentations, and commercial offers.',
      'Collaborate with marketing, product, and operations teams to align on sales strategy.',
      'Maintain accurate pipeline data in the CRM.',
      'Identify upsell and cross-sell opportunities within existing accounts.',
    ],
    requiredQualificationsBank: [
      'Sales experience with a track record of meeting or exceeding targets.',
      'Strong prospecting, negotiation, and closing skills.',
      'Excellent communication and presentation skills.',
      'Ability to manage a sales pipeline and stay organized across multiple opportunities.',
    ],
    preferredQualificationsBank: [
      'Experience selling in relevant industry or vertical.',
      'Experience with CRM platforms such as Salesforce, HubSpot, or Pipedrive.',
      'B2B or enterprise sales experience preferred for senior roles.',
    ],
    skills: ['prospecting', 'negotiation', 'closing', 'relationship management', 'pipeline management', 'presentation', 'CRM usage'],
    tools: ['Salesforce', 'HubSpot', 'Pipedrive', 'LinkedIn Sales Navigator', 'Google Workspace', 'Zoom'],
    interviewQuestionBank: [
      'Walk us through your sales process from first contact to close.',
      'Tell us about a deal you are most proud of closing and what made it challenging.',
      'How do you manage a pipeline with many opportunities at different stages?',
      'Describe how you handle objections from a prospective client.',
    ],
    videoPromptBank: [
      'Pitch us on why you are the right person for this sales role.',
      'Describe the approach you use to build rapport with a prospect you\'ve never met.',
      'How do you stay motivated and maintain performance during a slow sales period?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
      { badge: 'Commission-Based', condition: 'if commission structure mentioned' },
    ],
    educationNote: 'No degree required unless employer states.',
    experienceNote: 'Sales track record more important than educational background.',
    fakeClaims: ['salary', 'commission structure', 'territory size', 'specific client names'],
    variationProfiles: ['standard_candidate_friendly', 'senior_operations_leadership'],
  },

  // ── Marketing / Communications ────────────────────────────────────────────────
  marketing_communications: {
    id: 'marketing_communications',
    label: 'Marketing / Communications',
    responsibilitiesBank: [
      'Plan and execute integrated marketing campaigns across digital and offline channels.',
      'Develop and manage content for social media, email, website, and marketing materials.',
      'Support brand messaging, positioning, and communications strategy.',
      'Track and analyze campaign performance using analytics and reporting tools.',
      'Coordinate with design, product, sales, and leadership on marketing initiatives.',
      'Manage relationships with media, PR agencies, and external creative partners.',
      'Create presentations, proposals, and marketing collateral.',
      'Monitor market trends, competitor activity, and customer insights.',
    ],
    requiredQualificationsBank: [
      'Marketing experience across digital or traditional channels.',
      'Strong written and verbal communication skills.',
      'Experience with content creation, social media management, or campaign execution.',
      'Ability to analyze marketing data and extract actionable insights.',
      'Organized and able to manage multiple campaigns simultaneously.',
    ],
    preferredQualificationsBank: [
      'Experience with marketing automation tools, CRM, or email marketing platforms.',
      'SEO, SEM, or paid media experience.',
      'Experience in relevant industry or audience segment.',
      'Graphic design skills or experience with Canva, Adobe, or Figma.',
    ],
    skills: ['campaign management', 'content creation', 'social media', 'copywriting', 'SEO', 'analytics', 'brand communication', 'digital marketing'],
    tools: ['Meta Business Suite', 'Google Analytics', 'Mailchimp', 'Canva', 'HubSpot', 'Hootsuite', 'WordPress'],
    interviewQuestionBank: [
      'Walk us through a campaign you planned and executed. What were the results?',
      'How do you measure the success of a marketing campaign?',
      'Describe how you develop a content calendar and manage production.',
      'What marketing channels have you used, and which have driven the best results for you?',
    ],
    videoPromptBank: [
      'Walk us through a campaign you are proud of and what made it successful.',
      'How do you balance creativity with data when making marketing decisions?',
      'Describe your process for creating a piece of content from brief to publish.',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No specific degree required; portfolio of work preferred.',
    experienceNote: 'Campaign or content experience; digital skills preferred.',
    fakeClaims: ['salary', 'specific platform expertise', 'reach or follower claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },

  // ── Operations / Logistics ────────────────────────────────────────────────────
  operations_logistics: {
    id: 'operations_logistics',
    label: 'Operations / Logistics',
    responsibilitiesBank: [
      'Manage day-to-day operations workflows, processes, and team coordination.',
      'Monitor operational KPIs and implement improvements to efficiency and quality.',
      'Coordinate logistics, supply chain, or fulfillment activities.',
      'Track inventory, warehouse operations, or distribution schedules.',
      'Work with vendors, suppliers, and carriers on service delivery.',
      'Prepare operations reports, dashboards, and management updates.',
      'Identify process gaps and lead improvement initiatives.',
      'Coordinate with cross-functional teams on operational deliverables.',
    ],
    requiredQualificationsBank: [
      'Operations or logistics coordination experience.',
      'Strong organizational and analytical skills.',
      'Ability to manage multiple priorities and meet deadlines.',
      'Clear communication with internal teams, vendors, and stakeholders.',
    ],
    preferredQualificationsBank: [
      'Experience in supply chain, warehouse, or fulfillment operations.',
      'Experience with ERP or operations management systems.',
      'Data analysis or reporting experience for operations dashboards.',
    ],
    skills: ['process improvement', 'logistics coordination', 'inventory management', 'reporting', 'supplier management', 'operations analysis'],
    tools: ['SAP', 'Oracle', 'Google Workspace', 'Microsoft Excel', 'Trello', 'ERP systems'],
    interviewQuestionBank: [
      'Describe a process improvement you implemented that had measurable results.',
      'How do you handle supply chain disruptions or vendor issues?',
      'Walk us through how you manage a complex logistics or fulfillment operation.',
    ],
    videoPromptBank: [
      'Walk us through a complex operations challenge you solved.',
      'How do you prioritize when multiple operational issues occur at the same time?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No degree requirement unless employer states.',
    experienceNote: 'Operations experience; supply chain or logistics preferred for specialist roles.',
    fakeClaims: ['salary', 'specific ERP', 'headcount managed', 'warehouse size'],
    variationProfiles: ['standard_candidate_friendly', 'senior_operations_leadership'],
  },

  // ── Product / Project Management ─────────────────────────────────────────────
  project_product_mgmt: {
    id: 'project_product_mgmt',
    label: 'Product / Project Management',
    responsibilitiesBank: [
      'Define project scope, objectives, timelines, and deliverables.',
      'Track project progress, manage risks, and escalate blockers.',
      'Facilitate sprint planning, stand-ups, retrospectives, and stakeholder updates.',
      'Coordinate cross-functional teams including engineering, design, and business stakeholders.',
      'Maintain project documentation, RAID logs, and status reports.',
      'Manage product roadmaps, feature prioritization, and release planning.',
      'Gather and translate user and stakeholder requirements into actionable tasks.',
      'Measure project outcomes and report on KPIs post-delivery.',
    ],
    requiredQualificationsBank: [
      'Project management or product coordination experience.',
      'Strong organizational and communication skills.',
      'Ability to manage cross-functional teams and multiple concurrent projects.',
      'Experience with agile, scrum, or structured project management methodologies.',
      'Strong documentation and reporting skills.',
    ],
    preferredQualificationsBank: [
      'PMP, PRINCE2, or Scrum Master certification preferred.',
      'Experience in product management with roadmap and backlog ownership.',
      'Experience managing enterprise or government projects.',
    ],
    skills: ['project planning', 'risk management', 'stakeholder management', 'agile', 'scrum', 'documentation', 'delivery management'],
    tools: ['Jira', 'Asana', 'Monday.com', 'Trello', 'Confluence', 'Microsoft Project', 'Notion'],
    interviewQuestionBank: [
      'Walk us through a complex project you managed from planning to delivery.',
      'How do you handle scope creep or changing requirements mid-project?',
      'Describe your approach to keeping cross-functional teams aligned and accountable.',
      'How do you manage a project that is running behind schedule?',
    ],
    videoPromptBank: [
      'Walk us through a project you delivered successfully and what made it challenging.',
      'How do you balance delivery speed with quality?',
      'Describe how you communicate project status to leadership and technical teams.',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No degree requirement; certification preferred for senior roles.',
    experienceNote: 'Project coordination or product management experience based on seniority.',
    fakeClaims: ['salary', 'specific methodology requirement', 'project budget claims'],
    variationProfiles: ['standard_candidate_friendly', 'technical_delivery'],
  },

  // ── Customer Success / Account Management ────────────────────────────────────
  customer_success: {
    id: 'customer_success',
    label: 'Customer Success / Account Management',
    responsibilitiesBank: [
      'Own and manage a portfolio of customer accounts from onboarding to renewal.',
      'Build strong long-term relationships with clients through regular touchpoints.',
      'Drive product adoption, value realization, and customer satisfaction.',
      'Identify upsell, cross-sell, and expansion opportunities within existing accounts.',
      'Monitor health scores, engagement signals, and churn risk indicators.',
      'Coordinate with product, support, and sales teams on customer needs.',
      'Prepare quarterly business reviews, success plans, and account reporting.',
      'Escalate and resolve customer issues with urgency and ownership.',
    ],
    requiredQualificationsBank: [
      'Customer success, account management, or client relations experience.',
      'Strong relationship management and communication skills.',
      'Ability to manage multiple accounts and priorities.',
      'Experience driving customer retention and satisfaction.',
    ],
    preferredQualificationsBank: [
      'Experience with customer success platforms such as Gainsight or ChurnZero.',
      'Experience in SaaS, technology, or subscription-based businesses.',
      'Experience with enterprise or government account portfolios.',
    ],
    skills: ['onboarding', 'relationship management', 'retention', 'product adoption', 'reporting', 'issue escalation', 'account health monitoring'],
    tools: ['Gainsight', 'Salesforce', 'HubSpot', 'Zendesk', 'Google Workspace', 'Zoom'],
    interviewQuestionBank: [
      'How do you identify at-risk accounts and what do you do to prevent churn?',
      'Walk us through how you onboard a new customer to ensure long-term success.',
      'Describe a situation where you turned around a difficult customer relationship.',
    ],
    videoPromptBank: [
      'How do you proactively build trust with a new client from day one?',
      'Describe a customer win you are proud of and what you did to achieve it.',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'No degree requirement unless employer states.',
    experienceNote: 'Account management or customer success experience.',
    fakeClaims: ['salary', 'churn rate claims', 'NPS score claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },

  // ── Executive / Leadership ────────────────────────────────────────────────────
  executive_leadership: {
    id: 'executive_leadership',
    label: 'Executive / Leadership',
    responsibilitiesBank: [
      'Define and drive organizational strategy, vision, and business objectives.',
      'Lead, develop, and manage senior leadership teams and cross-functional departments.',
      'Build and maintain relationships with key stakeholders, partners, and clients.',
      'Oversee financial performance, budgets, and resource allocation.',
      'Drive organizational growth, market expansion, and operational excellence.',
      'Represent the organization externally to clients, investors, government, and the public.',
      'Ensure regulatory compliance and risk management across business operations.',
    ],
    requiredQualificationsBank: [
      'Senior leadership experience in a relevant industry or function.',
      'Strong strategic planning and business development capabilities.',
      'Track record of delivering business results through teams.',
      'Excellent communication, stakeholder management, and executive presence.',
    ],
    preferredQualificationsBank: [
      'Board or investor relations experience.',
      'Experience leading organizational transformation or change management.',
      'P&L ownership experience.',
    ],
    skills: ['strategic leadership', 'stakeholder management', 'P&L management', 'team development', 'business development', 'change management'],
    tools: ['Board reporting tools', 'ERP platforms', 'Financial dashboards', 'Microsoft Suite'],
    interviewQuestionBank: [
      'Describe the most significant organizational challenge you have led and what you learned.',
      'How do you build and develop high-performing senior leadership teams?',
      'Walk us through your approach to strategy development and execution.',
    ],
    videoPromptBank: [
      'What is the most important leadership lesson you have learned in your career?',
      'How do you create alignment across large teams or diverse stakeholders?',
    ],
    badgeSuggestionRules: [
      { badge: 'Salary Posted', condition: 'if salary supplied' },
    ],
    educationNote: 'Degree not always required; leadership track record more critical.',
    experienceNote: 'Senior leadership experience; years based on scope and seniority.',
    fakeClaims: ['salary', 'equity', 'specific company valuation'],
    variationProfiles: ['senior_operations_leadership'],
  },

  // ── Lightweight stubs for remaining 19 role families ────────────────────────
  creative_design_content: {
    id: 'creative_design_content', label: 'Creative / Design / Content',
    responsibilitiesBank: ['Create compelling visual, content, and design assets.', 'Maintain brand consistency across deliverables.', 'Collaborate with marketing, product, and communications teams.', 'Manage creative production timelines.'],
    requiredQualificationsBank: ['Portfolio of relevant creative work.', 'Proficiency in design or content tools.', 'Strong attention to visual detail and brand guidelines.'],
    preferredQualificationsBank: ['Experience with Adobe Creative Suite, Figma, or similar.', 'Experience in a creative agency or in-house team.'],
    skills: ['graphic design', 'content creation', 'visual communication', 'brand design', 'UI/UX', 'typography'],
    tools: ['Adobe Creative Suite', 'Figma', 'Canva', 'After Effects', 'Premier Pro'],
    interviewQuestionBank: ['Walk us through your portfolio.', 'How do you approach a new creative brief?'],
    videoPromptBank: ['Show us a project you are proud of.', 'How do you handle creative feedback?'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'Portfolio more important than degree.', experienceNote: 'Creative portfolio required.',
    fakeClaims: ['salary', 'follower counts', 'awards'], variationProfiles: ['standard_candidate_friendly'],
  },
  legal_compliance: {
    id: 'legal_compliance', label: 'Legal / Compliance',
    responsibilitiesBank: ['Ensure regulatory and legal compliance across operations.', 'Review, draft, and manage contracts and legal documents.', 'Support corporate governance and risk management.', 'Coordinate with regulatory bodies and legal counsel.'],
    requiredQualificationsBank: ['Legal, compliance, or paralegal experience.', 'Knowledge of relevant regulations in the Philippines.', 'Strong documentation and analytical skills.'],
    preferredQualificationsBank: ['Bar passage or law degree for lawyer roles.', 'Experience in corporate, commercial, or labor law.'],
    skills: ['legal research', 'contract review', 'compliance management', 'regulatory affairs', 'documentation'],
    tools: ['Legal databases', 'Microsoft Office', 'DocuSign', 'compliance management platforms'],
    interviewQuestionBank: ['How do you stay current on regulatory changes?', 'Describe a compliance risk you identified and resolved.'],
    videoPromptBank: ['How do you advise business teams on legal risks?'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'Law degree required for Lawyer roles; not required for Compliance Analyst roles.',
    experienceNote: 'Legal or compliance experience based on seniority.',
    fakeClaims: ['salary', 'specific regulatory framework claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },
  procurement_supply_chain: {
    id: 'procurement_supply_chain', label: 'Procurement / Supply Chain',
    responsibilitiesBank: ['Source and evaluate suppliers and vendor partners.', 'Manage purchase orders, contracts, and procurement workflows.', 'Optimize supply chain costs and delivery performance.'],
    requiredQualificationsBank: ['Procurement or purchasing experience.', 'Vendor management and negotiation skills.', 'Supply chain or inventory knowledge.'],
    preferredQualificationsBank: ['ERP system experience.', 'Experience in strategic sourcing or category management.'],
    skills: ['procurement', 'vendor management', 'negotiation', 'purchase order management', 'supply chain'],
    tools: ['SAP Ariba', 'Oracle Procurement', 'ERP platforms', 'Microsoft Excel'],
    interviewQuestionBank: ['How do you evaluate and select a new supplier?', 'Describe a cost-saving initiative you led.'],
    videoPromptBank: ['Walk us through a complex procurement scenario you managed.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required unless employer states.', experienceNote: 'Procurement or purchasing experience.',
    fakeClaims: ['salary', 'specific vendor names'], variationProfiles: ['standard_candidate_friendly'],
  },
  retail_store_ops: {
    id: 'retail_store_ops', label: 'Retail / Store Operations',
    responsibilitiesBank: ['Manage store or branch operations and team performance.', 'Drive sales targets and deliver an excellent customer experience.', 'Maintain store standards, inventory, and visual merchandising.'],
    requiredQualificationsBank: ['Retail or store operations experience.', 'Customer service mindset.', 'Ability to meet sales targets.'],
    preferredQualificationsBank: ['Store management experience.', 'Merchandising or inventory management skills.'],
    skills: ['retail operations', 'customer service', 'sales', 'inventory management', 'team leadership'],
    tools: ['POS systems', 'inventory management platforms', 'Microsoft Excel'],
    interviewQuestionBank: ['How do you motivate a retail team during slow sales periods?', 'How do you handle a difficult customer?'],
    videoPromptBank: ['Walk us through how you manage your store during a busy period.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required.', experienceNote: 'Retail experience based on seniority.',
    fakeClaims: ['salary', 'commission structure'], variationProfiles: ['standard_candidate_friendly'],
  },
  real_estate_property: {
    id: 'real_estate_property', label: 'Real Estate / Property',
    responsibilitiesBank: ['Market and sell or lease real estate properties.', 'Build a network of buyers, sellers, and landlords.', 'Prepare property listings, contracts, and supporting documents.'],
    requiredQualificationsBank: ['Real estate sales or property management experience.', 'Strong negotiation and communication skills.'],
    preferredQualificationsBank: ['PRC real estate broker license preferred.', 'Knowledge of local property market.'],
    skills: ['real estate sales', 'negotiation', 'property listing', 'client relations'],
    tools: ['Property listing platforms', 'Microsoft Office', 'CRM platforms'],
    interviewQuestionBank: ['How do you generate leads as a real estate professional?', 'Describe a complex property transaction you managed.'],
    videoPromptBank: ['How do you build trust with a buyer or seller?'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }, { badge: 'Commission-Based', condition: 'if commission mentioned' }],
    educationNote: 'PRC license required only if employer states.', experienceNote: 'Real estate sales or property experience.',
    fakeClaims: ['salary', 'specific property value claims'], variationProfiles: ['standard_candidate_friendly'],
  },
  social_media_community: {
    id: 'social_media_community', label: 'Social Media / Community',
    responsibilitiesBank: ['Manage social media accounts and content calendar.', 'Grow and engage online communities.', 'Create, schedule, and publish content across platforms.', 'Monitor and report on social media performance.'],
    requiredQualificationsBank: ['Social media management experience.', 'Content creation and copywriting skills.', 'Understanding of social media analytics.'],
    preferredQualificationsBank: ['Experience with social media management tools.', 'Community building or moderation experience.'],
    skills: ['social media management', 'content creation', 'community engagement', 'analytics', 'copywriting'],
    tools: ['Meta Business Suite', 'Hootsuite', 'Buffer', 'Canva', 'TikTok Creator tools'],
    interviewQuestionBank: ['How do you grow a social media following organically?', 'Describe a successful social media campaign you managed.'],
    videoPromptBank: ['Walk us through your social media strategy for a new brand.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required; portfolio of content preferred.', experienceNote: 'Social media or content experience.',
    fakeClaims: ['follower counts', 'reach claims', 'salary'], variationProfiles: ['standard_candidate_friendly'],
  },
  data_analytics: {
    id: 'data_analytics', label: 'Data / Analytics',
    responsibilitiesBank: ['Collect, clean, and analyze data from multiple sources.', 'Build dashboards, reports, and visualizations for business stakeholders.', 'Identify trends, patterns, and insights to support decision-making.', 'Collaborate with teams to define metrics and KPIs.'],
    requiredQualificationsBank: ['Data analysis experience.', 'Proficiency in Excel, SQL, or BI tools.', 'Ability to translate data insights into clear business narratives.'],
    preferredQualificationsBank: ['Experience with Power BI, Tableau, or Looker.', 'Python or R programming experience.', 'Statistical analysis or predictive modeling experience.'],
    skills: ['data analysis', 'SQL', 'data visualization', 'Excel', 'business intelligence', 'reporting', 'statistics'],
    tools: ['Microsoft Excel', 'SQL', 'Power BI', 'Tableau', 'Google Analytics', 'Python', 'R'],
    interviewQuestionBank: ['Walk us through a data analysis project that influenced a business decision.', 'How do you clean and validate data before analysis?'],
    videoPromptBank: ['Show us how you would approach a new data analysis request.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required; skills and portfolio preferred.', experienceNote: 'Data analysis experience; tools proficiency.',
    fakeClaims: ['salary', 'specific tool requirement'], variationProfiles: ['technical_delivery'],
  },
  field_sales_merchandising: {
    id: 'field_sales_merchandising', label: 'Field Sales / Merchandising',
    responsibilitiesBank: ['Execute field sales routes and meet daily/weekly/monthly targets.', 'Ensure product visibility, display standards, and in-store presence.', 'Build relationships with store managers and trade partners.', 'Submit daily field reports and sales data.'],
    requiredQualificationsBank: ['Field sales or merchandising experience.', 'Strong results orientation.', 'Ability to work independently in the field.'],
    preferredQualificationsBank: ['Experience with FMCG, telco, or retail accounts.', 'Driver\'s license if required by employer.'],
    skills: ['field sales', 'merchandising', 'relationship management', 'product promotion', 'territory management'],
    tools: ['Mobile order apps', 'route planning apps', 'Microsoft Excel'],
    interviewQuestionBank: ['How do you plan and prioritize your daily field route?', 'Describe how you handle a store that is not stocking your products.'],
    videoPromptBank: ['Walk us through a typical field sales day.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required.', experienceNote: 'Field sales or territory coverage experience.',
    fakeClaims: ['salary', 'commission', 'specific FMCG brand', 'territory size'], variationProfiles: ['standard_candidate_friendly'],
  },
  construction_engineering: {
    id: 'construction_engineering', label: 'Construction / Engineering',
    responsibilitiesBank: ['Manage construction activities and project site operations.', 'Review and approve engineering drawings, BOQ, and technical specifications.', 'Coordinate with contractors, consultants, and project owners.', 'Ensure safety, quality, and compliance standards are met on site.'],
    requiredQualificationsBank: ['Engineering or construction management experience.', 'Knowledge of relevant engineering standards and regulations.', 'Site management or supervisory experience.'],
    preferredQualificationsBank: ['Licensed Engineer (PRC) preferred for engineer roles.', 'Experience with relevant software (AutoCAD, Civil 3D, Revit).'],
    skills: ['project management', 'site management', 'engineering', 'CAD', 'quality control', 'safety management'],
    tools: ['AutoCAD', 'Revit', 'Civil 3D', 'Primavera', 'MS Project'],
    interviewQuestionBank: ['Describe a complex construction project you managed.', 'How do you ensure safety compliance on a project site?'],
    videoPromptBank: ['Walk us through how you manage a construction project schedule.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'Engineering degree and PRC license may be required; mark for review if inferred.', experienceNote: 'Civil/structural/mechanical engineering experience.',
    fakeClaims: ['salary', 'project value claims'], variationProfiles: ['standard_candidate_friendly'],
  },
  hospitality_tourism: {
    id: 'hospitality_tourism', label: 'Hospitality / Tourism',
    responsibilitiesBank: ['Deliver exceptional guest experiences throughout the customer journey.', 'Handle check-in, check-out, reservations, and front desk operations.', 'Resolve guest concerns promptly and professionally.', 'Coordinate with F&B, housekeeping, and concierge teams.'],
    requiredQualificationsBank: ['Hospitality or customer service experience.', 'Strong communication and interpersonal skills.', 'Service excellence mindset.'],
    preferredQualificationsBank: ['Hotel or tourism industry experience.', 'Property management system (PMS) experience.'],
    skills: ['guest service', 'front desk operations', 'hospitality', 'communication', 'problem solving', 'reservation management'],
    tools: ['Opera PMS', 'Fidelio', 'Microsoft Office', 'reservation systems'],
    interviewQuestionBank: ['How do you handle a guest complaint?', 'Describe your experience managing front-desk operations during peak periods.'],
    videoPromptBank: ['Walk us through how you create a memorable guest experience.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'HM or Tourism degree preferred but not required.', experienceNote: 'Hotel or hospitality experience.',
    fakeClaims: ['salary', 'specific hotel brand claims'], variationProfiles: ['standard_candidate_friendly'],
  },
  manufacturing_production: {
    id: 'manufacturing_production', label: 'Manufacturing / Production',
    responsibilitiesBank: ['Oversee production operations and meet daily output targets.', 'Monitor quality control and ensure products meet specifications.', 'Coordinate with maintenance, quality, and logistics teams.', 'Ensure compliance with safety protocols on the production floor.'],
    requiredQualificationsBank: ['Manufacturing or production floor experience.', 'Quality awareness and safety mindset.', 'Ability to lead or work in a team environment.'],
    preferredQualificationsBank: ['Experience in lean manufacturing or 5S.', 'Supervisory experience in a production environment.'],
    skills: ['production management', 'quality control', 'safety', 'lean manufacturing', 'team coordination'],
    tools: ['ERP systems', 'production management software', 'quality management tools'],
    interviewQuestionBank: ['How do you handle a production line stoppage?', 'Describe how you maintain quality standards during high-volume production.'],
    videoPromptBank: ['Walk us through how you manage a production team.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'Technical or engineering degree may be required for supervisory roles; mark for review.',
    experienceNote: 'Production or manufacturing experience.', fakeClaims: ['salary', 'production capacity claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },
  security_safety: {
    id: 'security_safety', label: 'Security / Safety',
    responsibilitiesBank: ['Maintain security operations and enforce access control.', 'Monitor premises using CCTV, patrols, and security systems.', 'Respond to incidents and coordinate emergency procedures.', 'Prepare security reports and incident logs.'],
    requiredQualificationsBank: ['Security or safety officer experience.', 'SOSIA license for security guard roles (verify requirement).', 'Alert, reliable, and professional demeanor.'],
    preferredQualificationsBank: ['CCTV or security system monitoring experience.', 'First aid certification preferred.'],
    skills: ['security operations', 'access control', 'incident management', 'patrol', 'CCTV monitoring', 'reporting'],
    tools: ['CCTV systems', 'access control systems', 'security management platforms'],
    interviewQuestionBank: ['How do you respond to a security incident on premises?', 'Describe your experience with access control procedures.'],
    videoPromptBank: ['Walk us through how you would handle a security emergency.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'SOSIA license mark for review — confirm requirement with employer.',
    experienceNote: 'Security or safety officer experience.', fakeClaims: ['salary', 'SOSIA claim without employer confirmation'],
    variationProfiles: ['standard_candidate_friendly'],
  },
  transportation_fleet: {
    id: 'transportation_fleet', label: 'Transportation / Fleet',
    responsibilitiesBank: ['Operate or manage fleet vehicles safely and reliably.', 'Manage vehicle maintenance schedules and driver coordination.', 'Ensure on-time delivery and route adherence.'],
    requiredQualificationsBank: ['Valid driver\'s license (professional or non-professional based on role).', 'Experience in driving, dispatching, or fleet coordination.', 'Strong sense of responsibility and safety awareness.'],
    preferredQualificationsBank: ['Experience managing a fleet or logistics routes.', 'Familiarity with GPS or fleet management systems.'],
    skills: ['driving', 'fleet management', 'dispatching', 'route planning', 'vehicle maintenance coordination'],
    tools: ['GPS apps', 'fleet management systems', 'communication radios'],
    interviewQuestionBank: ['How do you ensure on-time and safe delivery?', 'How do you handle unexpected route disruptions?'],
    videoPromptBank: ['Walk us through how you plan and execute a delivery route.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required; license is the key credential.', experienceNote: 'Driving or fleet coordination experience.',
    fakeClaims: ['salary', 'vehicle type claims'], variationProfiles: ['standard_candidate_friendly'],
  },
  business_process: {
    id: 'business_process', label: 'Business Process / Back Office',
    responsibilitiesBank: ['Process transactions, data, and documents accurately.', 'Follow standard operating procedures for back-office tasks.', 'Meet daily processing targets and quality standards.', 'Identify and report process errors or discrepancies.'],
    requiredQualificationsBank: ['Back-office, data processing, or administrative experience.', 'Strong attention to detail and accuracy.', 'Ability to follow structured workflows.'],
    preferredQualificationsBank: ['Experience in BPO or shared services environment.', 'Familiarity with process automation tools.'],
    skills: ['data processing', 'accuracy', 'attention to detail', 'process adherence', 'documentation'],
    tools: ['Microsoft Office', 'ERP platforms', 'BPO workflow systems'],
    interviewQuestionBank: ['How do you maintain accuracy under a high-volume processing workload?', 'Describe a process error you caught and fixed.'],
    videoPromptBank: ['Walk us through how you handle a high-volume processing task.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'No degree required.', experienceNote: 'Back-office or processing experience.',
    fakeClaims: ['salary', 'processing volume claims'], variationProfiles: ['standard_candidate_friendly'],
  },
  training_implementation: {
    id: 'training_implementation', label: 'Training / Implementation / Onboarding',
    responsibilitiesBank: ['Manage end-to-end product or system implementation for clients.', 'Conduct onboarding sessions, training workshops, and user walkthroughs.', 'Support clients through go-live activities and post-launch stabilization.', 'Create training materials, user guides, and onboarding documentation.'],
    requiredQualificationsBank: ['Implementation, training, or onboarding experience.', 'Strong presentation and facilitation skills.', 'Ability to simplify complex product or system concepts.'],
    preferredQualificationsBank: ['Experience with SaaS or enterprise software implementations.', 'Instructional design or curriculum development experience.'],
    skills: ['product training', 'implementation management', 'onboarding', 'facilitation', 'documentation', 'client engagement'],
    tools: ['Zoom', 'LMS platforms', 'Google Workspace', 'Jira', 'Confluence', 'screen recording tools'],
    interviewQuestionBank: ['Walk us through a full product implementation you managed.', 'How do you handle a client who is resistant to adopting a new system?'],
    videoPromptBank: ['Walk us through how you would onboard a new client to a complex product.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }, { badge: 'Training Provided', condition: 'if onboarding support mentioned' }],
    educationNote: 'No degree required.', experienceNote: 'Implementation or training experience.',
    fakeClaims: ['salary', 'specific implementation count claims'], variationProfiles: ['standard_candidate_friendly'],
  },

  // ── Catch-all fallback ────────────────────────────────────────────────────────
  _fallback: {
    id: '_fallback', label: 'General / Professional',
    responsibilitiesBank: ['Contribute effectively to the team\'s goals and deliverables.', 'Coordinate and communicate with stakeholders.', 'Prepare reports, documents, and updates.', 'Support daily operations and organizational objectives.'],
    requiredQualificationsBank: ['Relevant experience in this role or a similar function.', 'Strong communication and organizational skills.', 'Ability to meet deadlines and manage priorities.'],
    preferredQualificationsBank: ['Experience in a related industry or domain.', 'Relevant certifications or professional development.'],
    skills: ['communication', 'organization', 'problem solving', 'teamwork', 'documentation'],
    tools: ['Microsoft Office', 'Google Workspace', 'communication platforms'],
    interviewQuestionBank: ['Tell us about your relevant experience and how it applies to this role.', 'How do you handle competing priorities?'],
    videoPromptBank: ['Walk us through why you are the right person for this role.'],
    badgeSuggestionRules: [{ badge: 'Salary Posted', condition: 'if salary supplied' }],
    educationNote: 'Confirm with employer.', experienceNote: 'Relevant experience based on seniority.',
    fakeClaims: ['salary', 'company claims', 'industry claims'],
    variationProfiles: ['standard_candidate_friendly'],
  },
};

export function getRoleTemplate(familyId) {
  var id = familyId || '_fallback';
  return TEMPLATES[id] || TEMPLATES['_fallback'];
}

export function getAllFamilyIds() {
  return Object.keys(TEMPLATES).filter(function(k) { return k !== '_fallback'; });
}
