-- Migration: image_variants table
-- GetHired image optimization pipeline — stores metadata for every
-- optimized image variant generated by imageProcessingService.
-- 2026-06-28

CREATE TABLE IF NOT EXISTS gethired.image_variants (
  id                   UUID         PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_type           VARCHAR(50)  NOT NULL,        -- 'company' | 'job' | 'user'
  owner_id             VARCHAR(255) NOT NULL,         -- companyId / jobId / uid
  company_id           VARCHAR(255) NULL,
  job_id               VARCHAR(255) NULL,
  purpose              VARCHAR(50)  NOT NULL,         -- company_logo | job_banner | ...
  original_filename_safe VARCHAR(255) NULL,
  original_storage_path  VARCHAR(500) NULL,
  original_size_bytes  INTEGER      NULL,
  original_width       INTEGER      NULL,
  original_height      INTEGER      NULL,
  original_mime        VARCHAR(100) NULL,
  processed_status     VARCHAR(20)  NOT NULL DEFAULT 'processed', -- processed | failed
  variant_json         JSONB        NULL,             -- array of variant objects
  primary_variant_key  VARCHAR(100) NULL,
  primary_url          TEXT         NULL,             -- cached primary display URL
  sha256               VARCHAR(64)  NULL,
  savings_bytes        INTEGER      NULL,
  savings_percent      NUMERIC(5,2) NULL,
  created_by           VARCHAR(255) NULL,
  created_at           TIMESTAMP    NOT NULL DEFAULT NOW(),
  updated_at           TIMESTAMP    NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_image_variants_owner
  ON gethired.image_variants (owner_type, owner_id);

CREATE INDEX IF NOT EXISTS idx_image_variants_purpose
  ON gethired.image_variants (purpose);

CREATE INDEX IF NOT EXISTS idx_image_variants_company
  ON gethired.image_variants (company_id) WHERE company_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_image_variants_job
  ON gethired.image_variants (job_id) WHERE job_id IS NOT NULL;
