'use strict';
const events = [
'TRIAL_STARTED','TRIAL_ACTIVATED','TRIAL_DAY_3','TRIAL_7_DAYS_REMAINING','TRIAL_3_DAYS_REMAINING','TRIAL_1_DAY_REMAINING','TRIAL_EXPIRED','TRIAL_CONVERTED',
'JOB_USAGE_50_PERCENT','JOB_USAGE_80_PERCENT','JOB_USAGE_100_PERCENT','JOB_LIMIT_REACHED',
'STORAGE_USAGE_50_PERCENT','STORAGE_USAGE_70_PERCENT','STORAGE_USAGE_80_PERCENT','STORAGE_USAGE_90_PERCENT','STORAGE_USAGE_100_PERCENT','STORAGE_LIMIT_REACHED',
'USER_USAGE_80_PERCENT','USER_USAGE_100_PERCENT','USER_LIMIT_REACHED','VIDEO_QUESTION_USAGE_80_PERCENT','VIDEO_QUESTION_LIMIT_REACHED',
'PREMIUM_FEATURE_ATTEMPTED','PRICING_PAGE_VIEWED','UPGRADE_PAGE_VIEWED','UPGRADE_STARTED','UPGRADE_COMPLETED','UPGRADE_ABANDONED',
'PAYMENT_FAILED','PAYMENT_RETRY_FAILED','PAYMENT_RECOVERED','SUBSCRIPTION_PAST_DUE','RENEWAL_APPROACHING','SUBSCRIPTION_RENEWED','STORAGE_ADDON_ACTIVATED',
'DOWNGRADE_REQUESTED','CANCELLATION_REQUESTED','SUBSCRIPTION_CANCELLED','HIGH_HIRING_ACTIVITY','PLAN_RECOMMENDATION_CHANGED','ENTERPRISE_SIGNAL_DETECTED','ACCOUNT_SNAPSHOT'
];
const browserEvents = ['PRICING_PAGE_VIEWED','UPGRADE_PAGE_VIEWED'];
const features = ['SSO','API','MULTI_BRAND','CUSTOM_INTEGRATION'];
function validateEvent(e) {
  if (!e || !events.includes(e.type) || typeof e.key !== 'string' || !e.key.length || e.key.length > 200) throw Object.assign(new Error('Invalid engagement event'), { code: 'INVALID_EVENT' });
  if (e.feature && !features.includes(e.feature)) throw Object.assign(new Error('Invalid feature'), { code: 'INVALID_EVENT' });
  return { type: e.type, key: e.key, actorUid: e.actorUid || null, feature: e.feature || null, notificationId: e.notificationId || null };
}
module.exports = { events, browserEvents, features, validateEvent };
